theme: minima
title: Thanushree | React.js Developer
author: Thanushree M
description: Frontend developer passionate about building responsive and user-friendly web applications using React.js, JavaScript, and TypeScript.
theme: minima
